[package]
name = "robot_simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
itertools-num = "0.1.3"
plotters = "0.3.4"
